# Generated by Django 5.2.7 on 2025-12-12 19:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_code', models.CharField(help_text='Ex: Q1, Q2, ...', max_length=50, unique=True, verbose_name='Code de la question')),
                ('enonce_fr', models.TextField(verbose_name='Énoncé (Français)')),
                ('enonce_en', models.TextField(blank=True, verbose_name='Énoncé (Anglais)')),
                ('enonce_ar', models.TextField(blank=True, verbose_name='Énoncé (Arabe)')),
                ('reponse_correcte', models.BooleanField(help_text='Cochez si la réponse correcte est VRAI', verbose_name='Réponse correcte')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Question qui doit être obligatoirement réussie', verbose_name='Question obligatoire')),
                ('points', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Points pour bonne réponse')),
                ('image', models.ImageField(blank=True, help_text='Image optionnelle pour illustrer la question', null=True, upload_to='questions/hse/', verbose_name="Image d'illustration")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Question HSE',
                'verbose_name_plural': 'Questions HSE',
                'ordering': ['question_code'],
                'indexes': [models.Index(fields=['is_active'], name='tests_quest_is_acti_36ddfa_idx'), models.Index(fields=['is_mandatory'], name='tests_quest_is_mand_6f183a_idx'), models.Index(fields=['reponse_correcte'], name='tests_quest_reponse_486ba6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(choices=[(1, 'Version 1'), (2, 'Version 2'), (3, 'Version 3'), (4, 'Version 4'), (5, 'Version 5'), (6, 'Version 6')], unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Version du test')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duration_minutes', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Durée (minutes)')),
                ('total_questions', models.IntegerField(default=21, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre total de questions')),
                ('mandatory_questions_count', models.IntegerField(default=9, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(21)], verbose_name='Nombre de questions obligatoires')),
                ('passing_score_optional', models.IntegerField(default=9, help_text='Score minimum pour les questions optionnelles si les obligatoires sont réussies', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)], verbose_name='Score de passage questions optionnelles (%)')),
                ('ordre_questions', models.JSONField(help_text="Liste des IDs de questions dans l'ordre spécifique à cette version", verbose_name='Ordre des questions')),
                ('mandatory_questions', models.JSONField(default=list, help_text='Liste des IDs des questions obligatoires', verbose_name='Questions obligatoires')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Test HSE',
                'verbose_name_plural': 'Tests HSE',
                'ordering': ['version'],
                'indexes': [models.Index(fields=['is_active'], name='tests_test_is_acti_e3f3df_idx'), models.Index(fields=['version'], name='tests_test_version_536d2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(choices=[('ar', 'Arabe'), ('fr', 'Français'), ('en', 'Anglais')], default='ar', max_length=2, verbose_name='Langue du test')),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('passed', 'Réussi'), ('failed', 'Échoué')], default='in_progress', max_length=20, verbose_name='Statut')),
                ('mandatory_correct', models.IntegerField(default=0, verbose_name='Questions obligatoires correctes')),
                ('mandatory_wrong', models.IntegerField(default=0, verbose_name='Questions obligatoires incorrectes')),
                ('mandatory_total', models.IntegerField(default=9, verbose_name='Total questions obligatoires')),
                ('optional_correct', models.IntegerField(default=0, verbose_name='Questions optionnelles correctes')),
                ('optional_wrong', models.IntegerField(default=0, verbose_name='Questions optionnelles incorrectes')),
                ('optional_total', models.IntegerField(default=12, verbose_name='Total questions optionnelles')),
                ('mandatory_score_percentage', models.FloatField(default=0, verbose_name='Score questions obligatoires')),
                ('optional_score_percentage', models.FloatField(default=0, verbose_name='Score questions optionnelles')),
                ('overall_score_percentage', models.FloatField(default=0, verbose_name='Score global')),
                ('passed', models.BooleanField(default=False, verbose_name='Test réussi')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Débuté à')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé à')),
                ('time_taken_seconds', models.IntegerField(default=0, verbose_name='Temps pris (secondes)')),
                ('user_answers', models.JSONField(default=dict, help_text="Format: {question_id: {'answer': bool, 'is_mandatory': bool}}", verbose_name="Réponses de l'utilisateur")),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Tentative de test',
                'verbose_name_plural': 'Tentatives de test',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'test'], name='tests_testa_user_id_a9b45d_idx'), models.Index(fields=['completed_at'], name='tests_testa_complet_cf655c_idx'), models.Index(fields=['passed'], name='tests_testa_passed_47382a_idx'), models.Index(fields=['status'], name='tests_testa_status_ebfe54_idx'), models.Index(fields=['langue'], name='tests_testa_langue_36f22b_idx')],
                'unique_together': {('user', 'test')},
            },
        ),
    ]
