# Generated by Django 5.2.7 on 2025-12-15 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='total_questions',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre total de questions'),
        ),
        migrations.AlterField(
            model_name='test',
            name='version',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Version du test'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='user_answers',
            field=models.JSONField(default=dict, help_text="Format: {question_id: {'answer': bool, 'answer_text': str (dans la langue choisie), 'langue': str}}", verbose_name="Réponses de l'utilisateur"),
        ),
    ]
