# Generated by Django 5.2.7 on 2025-12-16 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_add_etat_field'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='test',
            new_name='tests_test_etat_fd8438_idx',
            old_name='tests_test_etat_idx',
        ),
        migrations.RenameIndex(
            model_name='testattempt',
            new_name='tests_testa_etat_9a581f_idx',
            old_name='tests_testat_etat_idx',
        ),
    ]
