# Generated by Django 5.2.7 on 2025-12-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testuser',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='testuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'Utilisateur HSE'), ('manager', 'Manager HSE')], default='user', max_length=10, verbose_name="Type d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='testuser',
            name='cin',
            field=models.CharField(max_length=20, unique=True, verbose_name='CIN'),
        ),
    ]
