version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hse_database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: hse_user
      MYSQL_PASSWORD: hse_password
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
      - ./reset_hse_tables.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    networks:
      - hse_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .               # Contexte = racine du projet
      dockerfile: backend/Dockerfile
    container_name: hse_backend
    restart: unless-stopped
    volumes:
      - .:/app                # Monte la racine du projet (pour avoir manage.py)
      - backend_static:/app/static
      - backend_media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-w2(c2(oo-ad&=878nqa2)5f884t^4jj&je^-4rw+503l4-9p!f
      - DATABASE_NAME=hse_database
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - ALLOWED_HOSTS=localhost,127.0.0.1,10.24.159.13,*,db,backend,frontend
      - FRONTEND_URL=http://10.24.159.13:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hse_network

  frontend:
    build:
      context: .                   # Contexte = racine du projet
      dockerfile: frontend/Dockerfile
    container_name: hse_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - hse_network

volumes:
  db_data:
    driver: local
  backend_static:
    driver: local
  backend_media:
    driver: local

networks:
  hse_network:
    driver: bridge