# Generated by Django 5.2.7 on 2025-12-02 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HSEManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du manager')),
                ('cin', models.CharField(max_length=50, unique=True, verbose_name='cin')),
            ],
            options={
                'verbose_name': 'Manager HSE',
                'verbose_name_plural': 'Managers HSE',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HSEUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prénom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('cin', models.CharField(max_length=20, unique=True, verbose_name='cin')),
                ('entite', models.CharField(max_length=100, verbose_name='Entité')),
                ('entreprise', models.CharField(max_length=100, verbose_name='Entreprise')),
                ('chef_projet_ocp', models.CharField(blank=True, max_length=100, verbose_name='Chef de projet OCP')),
                ('presence', models.BooleanField(default=False, verbose_name='Présent')),
                ('reussite', models.BooleanField(default=False, verbose_name='Réussi(e)')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)], verbose_name='Score global (%)')),
            ],
            options={
                'verbose_name': 'Utilisateur HSE',
                'verbose_name_plural': 'Utilisateurs HSE',
                'ordering': ['nom', 'prénom'],
                'indexes': [models.Index(fields=['nom', 'prénom'], name='hse_app_hse_nom_705c9c_idx'), models.Index(fields=['entite'], name='hse_app_hse_entite_d390b9_idx'), models.Index(fields=['entreprise'], name='hse_app_hse_entrepr_74a82f_idx')],
            },
        ),
    ]
