# Generated by Django 5.2.7 on 2025-12-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HSEManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('cin', models.CharField(max_length=50, unique=True, verbose_name='CIN')),
            ],
            options={
                'verbose_name': 'Manager HSE',
                'verbose_name_plural': 'Managers HSE',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='HSEUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prénom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('cin', models.CharField(max_length=20, unique=True, verbose_name='CIN')),
                ('entite', models.CharField(max_length=100, verbose_name='Entité')),
                ('entreprise', models.CharField(max_length=100, verbose_name='Entreprise')),
                ('chef_projet_ocp', models.CharField(blank=True, max_length=100, verbose_name='Chef de projet OCP')),
                ('reussite', models.BooleanField(default=False, verbose_name='Sensibilisé avec succès')),
            ],
            options={
                'verbose_name': 'Utilisateur HSE',
                'verbose_name_plural': 'Utilisateurs HSE',
                'ordering': ['nom', 'prénom'],
                'indexes': [models.Index(fields=['nom', 'prénom'], name='hse_app_hse_nom_705c9c_idx'), models.Index(fields=['entite'], name='hse_app_hse_entite_d390b9_idx'), models.Index(fields=['entreprise'], name='hse_app_hse_entrepr_74a82f_idx'), models.Index(fields=['cin'], name='hse_app_hse_cin_f242d9_idx')],
            },
        ),
    ]
