# Generated by Django 5.2.8 on 2025-11-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hseuser',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hseuser',
            name='presence',
            field=models.BooleanField(default=False),
        ),
    ]
