# Generated by Django 5.2.7 on 2025-12-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hseuser',
            old_name='reussite',
            new_name='presence',
        ),
    ]
