# Generated by Django 5.2.8 on 2025-11-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hse_app', '0002_hseuser_score_alter_hseuser_presence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hseuser',
            name='employee_id',
        ),
    ]
