# Generated by Django 5.2.7 on 2025-12-13 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_app', '0002_rename_reussite_to_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='hseuser',
            name='date_ajout',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='hseuser',
            name='presence',
            field=models.BooleanField(default=False, verbose_name='Présence'),
        ),
        migrations.AddIndex(
            model_name='hseuser',
            index=models.Index(fields=['date_ajout'], name='hse_app_hse_date_aj_45afc7_idx'),
        ),
    ]
