# Generated by Django 5.2.7 on 2025-12-13 10:07

import hse_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_app', '0003_add_date_ajout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hseuser',
            name='date_ajout',
            field=models.DateField(default=hse_app.models.get_today_date, verbose_name="Date d'ajout"),
        ),
    ]
