# Generated by Django 5.2.7 on 2025-12-02 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_app', '0003_remove_hseuser_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSEManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du manager')),
                ('cin', models.CharField(max_length=50, unique=True, verbose_name='cin')),
            ],
            options={
                'verbose_name': 'Manager HSE',
                'verbose_name_plural': 'Managers HSE',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='selected_options',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='test_attempt',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='session',
        ),
        migrations.AlterModelOptions(
            name='hseuser',
            options={'ordering': ['nom', 'prénom'], 'verbose_name': 'Utilisateur HSE', 'verbose_name_plural': 'Utilisateurs HSE'},
        ),
        migrations.RemoveField(
            model_name='hseuser',
            name='position',
        ),
        migrations.AddField(
            model_name='hseuser',
            name='reussite',
            field=models.BooleanField(default=False, verbose_name='Réussi(e)'),
        ),
        migrations.AlterField(
            model_name='hseuser',
            name='chef_projet_ocp',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chef de projet OCP'),
        ),
        migrations.AlterField(
            model_name='hseuser',
            name='cin',
            field=models.CharField(max_length=20, unique=True, verbose_name='cin'),
        ),
        migrations.AlterField(
            model_name='hseuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='hseuser',
            name='entite',
            field=models.CharField(max_length=100, verbose_name='Entité'),
        ),
        migrations.AlterField(
            model_name='hseuser',
            name='entreprise',
            field=models.CharField(max_length=100, verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='hseuser',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='hseuser',
            name='presence',
            field=models.BooleanField(default=False, verbose_name='Présent'),
        ),
        migrations.AlterField(
            model_name='hseuser',
            name='prénom',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='hseuser',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)], verbose_name='Score global (%)'),
        ),
        migrations.AddIndex(
            model_name='hseuser',
            index=models.Index(fields=['nom', 'prénom'], name='hse_app_hse_nom_705c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='hseuser',
            index=models.Index(fields=['entite'], name='hse_app_hse_entite_d390b9_idx'),
        ),
        migrations.AddIndex(
            model_name='hseuser',
            index=models.Index(fields=['entreprise'], name='hse_app_hse_entrepr_74a82f_idx'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
        migrations.DeleteModel(
            name='TestQuestion',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestAttempt',
        ),
    ]
