# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_app', '0004_fix_date_ajout_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='hseuser',
            name='sensibilise_avec_succes',
            field=models.BooleanField(default=False, verbose_name='Sensibilisé avec succès'),
        ),
    ]

