# Generated by Django 5.2.7 on 2025-12-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hse_app', '0004_hsemanager_remove_answer_question_and_more'),
    ]

    operations = [
    ]
