# Generated by Django 5.2.7 on 2025-12-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginLog',
        ),
    ]
