# Generated by Django 5.2.7 on 2025-12-15 22:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0002_alter_test_total_questions_alter_test_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro du certificat')),
                ('user_full_name', models.CharField(max_length=255, verbose_name='Nom complet (au moment du certificat)')),
                ('user_cin', models.CharField(max_length=20, verbose_name='CIN (au moment du certificat)')),
                ('test_version', models.IntegerField(verbose_name='Version du test réussi')),
                ('score', models.IntegerField(verbose_name='Score obtenu (/21)')),
                ('issued_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('expiry_date', models.DateField(help_text="Généralement 1 an après l'émission", verbose_name="Date d'expiration")),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Fichier PDF du certificat')),
                ('test_attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='tests.testattempt', verbose_name='Tentative de test')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'ordering': ['-issued_date'],
                'indexes': [models.Index(fields=['user_cin'], name='certificats_user_ci_15c188_idx'), models.Index(fields=['test_attempt'], name='certificats_test_at_082d4a_idx'), models.Index(fields=['issued_date'], name='certificats_issued__fd3af5_idx')],
            },
        ),
    ]
